version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile # Ajuste para diferenciar o Dockerfile do frontend
    container_name: frontend-container
    ports:
      - "8080:80" # Porta mapeada para o frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
